# redirecting the homepage

#root:
#    path: /
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        path: /admin
#        permanent: true


fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"


#### LOGIN AND PASSWORD RESET ####

pronto_mobile_login:
    path: /login
    schemes: [https]
    defaults:
        _controller: ProntoMobileBundle:Web\Authentication:login

pronto_mobile_logout:
    path: /logout
    schemes: [https]
    defaults:
        _controller: ProntoMobileBundle:Web\Authentication:logout

pronto_mobile_forgot_password:
    path: /password/reset
    schemes: [https]
    defaults:
        _controller: ProntoMobileBundle:Web\Authentication:resetPasswordForm

pronto_mobile_reset_password:
    path: /password/reset/{token}
    schemes: [https]
    defaults:
        _controller: ProntoMobileBundle:Web\Authentication:resetPassword

pronto_mobile_create_password:
    path: /password/create/{token}
    schemes: [https]
    defaults:
        _controller: ProntoMobileBundle:Web\Authentication:createPassword

pronto_mobile_app_users_reset_password:
    path: /users/app/password/reset/{token}
    schemes: [https]
    defaults:
        _controller: ProntoMobileBundle:Api\V1\AppUser:resetPassword


pronto_mobile_app_web_file:
    resource: "@ProntoMobileBundle/Resources/config/routing/web.yaml"
    prefix: /admin
    name_prefix: pronto_mobile_
    schemes: [https]

pronto_mobile_app_api_file:
    resource: "@ProntoMobileBundle/Resources/config/routing/api.yaml"
    prefix: /api
    name_prefix: pronto_mobile_
    schemes: [https]