# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Pronto\MobileBundle\:
        resource: '../../{Command,Controller,DataFixtures,EventListener,EventSubscriber,Middleware,Provider,Security,Service,Repository,Validator}'

    pronto_mobile.global.app:
        class: Pronto\MobileBundle\Service\ProntoMobile
        public: true

    #### TWIG EXTENSIONS ####
    Pronto\MobileBundle\Twig\:
        resource: '../../Twig'
        tags: ['twig.extension']


    #### PRONTO MOBILE DOCTRINE EVENT SUBSCRIBERS ####
    Pronto\MobileBundle\EventListener\HashPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Pronto\MobileBundle\EventListener\CustomerSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Pronto\MobileBundle\EventListener\AppVersionSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Pronto\MobileBundle\EventListener\NotificationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Pronto\MobileBundle\EventListener\AccessTokenSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Pronto\MobileBundle\EventListener\ApplicationVersionSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Pronto\MobileBundle\EventListener\PluginSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    #### PRONTO MOBILE DATA FIXTURES ####
    Pronto\MobileBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']
