# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Pronto\MobileBundle\:
        resource: '../../{Command,Controller,DataFixtures,EventListener,EventSubscriber,Provider,Repository,Security,Service}'

    pronto_mobile.global.app:
        class: Pronto\MobileBundle\Service\ProntoMobile

    #### TWIG EXTENSIONS ####
    Pronto\MobileBundle\Twig\AssetVersioning:
        tags: ['twig.extension']


    #### PRONTO MOBILE DOCTRINE EVENT LISTENERS ####
    Pronto\MobileBundle\EventListener\HashPasswordListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Pronto\MobileBundle\EventListener\CustomerListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    Pronto\MobileBundle\EventListener\NotificationListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Pronto\MobileBundle\EventListener\AccessTokenListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    Pronto\MobileBundle\EventListener\ApplicationVersionListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    Pronto\MobileBundle\EventListener\PluginListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }


    #### PRONTO MOBILE DATA FIXTURES ####
    Pronto\MobileBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']
