# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
#parameter_name: value

services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  Pronto\MobileBundle\Grant\ProntoClientCredentialsGrant: ~
  Pronto\MobileBundle\Grant\ProntoPasswordGrant: ~

  # Don't autowire, because the third argument is being set in the ProntoMobileExtension class
  Pronto\MobileBundle\Service\ProntoMobile:
    autowire: false
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@request_stack'
      - []

  Pronto\MobileBundle\:
    resource: '../../{Command,Controller,DataFixtures,EventListener,EventSubscriber,Middleware,Provider,Security,Service,Repository,Validator}'
    exclude: '../../Service/ProntoMobile.php'

  #### TWIG EXTENSIONS ####
  Pronto\MobileBundle\Twig\:
    resource: '../../Twig'
    tags: ['twig.extension']

  #### SERIALIZER ####
  Pronto\MobileBundle\Serializer\Normalizer\:
    resource: '../../Serializer/Normalizer'
    tags: ['serializer.normalizer']

  #### PRONTO MOBILE DATA FIXTURES ####
  Pronto\MobileBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']

  pronto_mobile_app_user_provider:
    class: Pronto\MobileBundle\Provider\AppUserProvider

  Pronto\MobileBundle\EventListener\OAuth\UserResolveListener:
    arguments:
      - '@pronto_mobile_app_user_provider'
      - '@security.password_hasher'
      - '@doctrine.orm.entity_manager'
      - '@security.token_storage'
    tags:
      - { name: kernel.event_listener, event: league.oauth2_server.event.user_resolve, method: onUserResolve }
