
api_v1_routes:
    resource: "@ProntoMobileBundle/Resources/config/routing/api/v1/api.yaml"
    prefix: /v1
    name_prefix: api_v1_
    schemes: [https]

api_vue_routes:
    resource: '../../../Controller/Api/Vue/'
    prefix: /vue
    name_prefix: api_vue_
    type: annotation
